n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('É alfabético?', n.isalpha())
print('É um número?', n.isnumeric())
print('É um valor alfanumérico?', n.isalnum())
print('Está em letras maiúsculas?', n.isupper())
print('Possui algum espaço?', n.isspace())
print('É um número decimal?', n.isdecimal())
print('Está em minúsculo?', n.islower())
print('Está capitalizada?', n.istitle())
